### ISSUE TITLE
(BUG) Devices being added twice?

### ISSUE THREAD

**Issue by THATDONFC** [tonesto7/homebridge-smartthings-v2#11]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The SmartApp and Device Handler are using the latest code available.
-  [x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 2
-  Mobile App Version(Not required):
-  SmartApp Version: 2.0.1
-  Device Handler Version:
-  Homebridge Version: Homebridge v2.4 / HOOBS v3.1.1
-  NodeJS Version:

## Expected Behavior
**Tell us what you think should be happening**
Select one device as sensor and other, add one device to homebridge
## Current Behavior
**What happens instead of the expected behavior?**
Plugin tries to create two devices for the same device.
## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Install the plugin through HOOBS interface
2. Install the smart app in ST Classic and select one device as sensor and the same device as other
3. Check logs, see that two devices are being added

## Context
**How has this issue affected you? What are you trying to accomplish?**
**Providing context helps us come up with a solution that is most useful in the real world**
I am trying to migrate from v1 to v2 of the homebridge-smartthings plugin.
I deleted the v1 plugin form homebridge and from the ST Classic app. I installed the new smart app per the instructions.
I installed the plugin through the HOOBS plugin GUI. I placed the config code in the config.json file as instructed.
When run, the plugin attempts to create two devices for the same device and I receive an error. 
I have tried to narrow this down to one specific issue but I am having a hard time. I was expecting v2 to work as v1 did, where I could add the same device to many device types and it would not produce duplicates. Maybe this is not the case?

---
Please include a copy of any relevant log output to assist in tracking down the bug
```
[Homebridge] [12/11/2019, 11:15:43 AM] Loaded config.json with 2 accessories and 4 platforms.
[Homebridge] [12/11/2019, 11:15:45 AM] Loaded plugin: homebridge-smartthings-v2
[Homebridge] [12/11/2019, 11:15:45 AM] Registering platform 'homebridge-smartthings-v2.SmartThings-v2'
[Homebridge] [12/11/2019, 11:15:45 AM] ---
[Homebridge] [12/11/2019, 11:15:46 AM] [SmartThings-v2] Initializing SmartThings-v2 platform...
[Homebridge] [12/11/2019, 11:15:46 AM][SmartThings-v2]INFO: Homebridge Version: 2.4
[Homebridge] [12/11/2019, 11:15:46 AM][SmartThings-v2]INFO: SmartThings-v2 Plugin Version: 2.0.1
[Homebridge] [12/11/2019, 11:15:46 AM][SmartThings-v2]INFO: Checking Package Version for Updates...
[Homebridge] [12/11/2019, 11:15:47 AM][SmartThings-v2]INFO: Fetching SmartThings-v2 Devices. NOTICE: This may take a moment if you have a large number of device data is being loaded!
[Homebridge] [12/11/2019, 11:15:47 AM][SmartThings-v2]DEBUG: Refreshing All Device Data
[Homebridge] [12/11/2019, 11:15:48 AM][SmartThings-v2]WARN: Devices to Remove: (0)
[Homebridge] [12/11/2019, 11:15:48 AM][SmartThings-v2]INFO: Devices to Update: (0)
[Homebridge] [12/11/2019, 11:15:48 AM][SmartThings-v2]GOOD: Devices to Create: (2)
[Homebridge] [12/11/2019, 11:15:48 AM][SmartThings-v2]DEBUG: Initializing New Device (Front Door Lock | ***)
[Homebridge] [12/11/2019, 11:15:48 AM][SmartThings-v2]DEBUG: Removing capability: None from Device: Front Door Lock
[Homebridge] HAP Warning: Characteristic 0000001A-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000045-0000-1000-8000-0026BB765291. Adding anyway.
[Homebridge] [12/11/2019, 11:15:48 AM][SmartThings-v2]DEBUG:
[Homebridge] [12/11/2019, 11:15:48 AM][SmartThings-v2]DEBUG: Setting device data from existing data
[Homebridge] [12/11/2019, 11:15:48 AM][SmartThings-v2]NOTICE: [CHARACTERISTIC (BatteryLevel) CHANGE] battery (Front Door Lock) | LastUpdate: (Wed Dec 11 2019 11:15:48 GMT-0800 (Pacific Standard Time)) | NewValue: (100) | OldValue: (0)
[Homebridge] [12/11/2019, 11:15:48 AM][SmartThings-v2]INFO: Added Device: (Front Door Lock | ***)
[Homebridge] [12/11/2019, 11:15:48 AM][SmartThings-v2]DEBUG: Initializing New Device (Front Door Lock | ***)
[Homebridge] [12/11/2019, 11:15:48 AM][SmartThings-v2]DEBUG: Removing capability: None from Device: Front Door Lock
[Homebridge] HAP Warning: Characteristic 0000001A-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000045-0000-1000-8000-0026BB765291. Adding anyway.
[Homebridge] [12/11/2019, 11:15:48 AM][SmartThings-v2]DEBUG:
[Homebridge] [12/11/2019, 11:15:48 AM][SmartThings-v2]DEBUG: Setting device data from existing data
[Homebridge] [12/11/2019, 11:15:48 AM][SmartThings-v2]NOTICE: [CHARACTERISTIC (BatteryLevel) CHANGE] battery (Front Door Lock) | LastUpdate: (Wed Dec 11 2019 11:15:48 GMT-0800 (Pacific Standard Time)) | NewValue: (100) | OldValue: (0)
[Homebridge] [12/11/2019, 11:15:48 AM] Unhandled Rejection "Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: devUUID".
[Homebridge] [12/11/2019, 11:15:48 AM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: devUUID
[Homebridge] at Bridge.Accessory.addBridgedAccessory (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:268:13)
[Homebridge] at Bridge.Accessory.addBridgedAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:299:10)
[Homebridge] at Server._handleRegisterPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:503:18)
[Homebridge] at Server.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:33:14)
[Homebridge] at API.emit (events.js:198:13)
[Homebridge] at API.registerPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:154:10)
[Homebridge] at ST_Platform.addDevice (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/src/ST_Platform.js:182:25)
[Homebridge] at toCreate.forEach.device (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/src/ST_Platform.js:147:61)
[Homebridge] at Array.forEach (<anonymous>)
[Homebridge] at client.getDevices.catch.then.resp (/home/hoobs/.hoobs/node_modules/homebridge-smartthings-v2/src/ST_Platform.js:147:38)
[Homebridge] at process._tickCallback (internal/process/next_tick.js:68:7)
[Homebridge] (node:2643) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[Homebridge] [12/11/2019, 11:15:48 AM][SmartThings-v2]INFO: INFO: Your plugin version is up-to-date
[Homebridge] [12/11/2019, 11:15:49 AM][SmartThings-v2]DEBUG: sendUpdateStatus Resp:
```

**Comment by THATDONFC** [comment]
I just tried to reproduce the issue in v1.5.15 with the original smart app. Everything was set up correctly and the device was added successfully with 0 errors.

In the old version of the smart app I added the lock as a "sensor" and "other" just as I tried to do in v2 of the app. The device was added as I expected it to, as one device.

```
[Homebridge] [12/11/2019, 11:56:28 AM] Loaded config.json with 2 accessories and 4 platforms.
[Homebridge] [12/11/2019, 11:56:30 AM] Loaded plugin: homebridge-smartthings-tonesto7
[Homebridge] Homebridge Version: 2.4
[Homebridge] [12/11/2019, 11:56:30 AM] Registering platform 'homebridge-smartthings.SmartThings'
[Homebridge] [12/11/2019, 11:56:31 AM] [SmartThings] Initializing SmartThings platform...
[Homebridge] [12/11/2019, 11:56:31 AM] [SmartThings] Fetching SmartThings devices.
[Homebridge] [12/11/2019, 11:56:32 AM] [SmartThings] Unknown Capabilities: ["Smoke Detector"]
[Homebridge] [12/11/2019, 11:56:32 AM] [SmartThings] Initializing platform accessory 'Front Door Lock'...
[Homebridge] [12/11/2019, 11:56:32 AM] [SmartThings] update_method: direct
[Homebridge] [12/11/2019, 11:56:32 AM] [SmartThings] SmartThings Hub Communication Established
```

**Comment by tonesto7** [comment]
I'm not sure if you've modified any code or didn't follow the instructions but the responses i'm seeing here make no sense to me.  devUUID is not a value set by any of my code

**Comment by THATDONFC** [comment]
Its the UUID of the device. I removed it from the logs because I'm wasn't sure if it was sensitive information that shouldn't be shared publicly. Sorry I didn't clarify that.

**Comment by tonesto7** [comment]
This shouldn't be able to create duplicates.  I even added protections for it.  
Did you remove the accessories and persist folder for where the config.json is stored?

**Comment by THATDONFC** [comment]
Well, I just accidentally nuked my ST hub. So I'm going to start fresh and try to install everything from scratch. I'll update this when I am back home and able to add all of my devices back to my ST hub.

**Comment by THATDONFC** [comment]
I want to be sure I'm setting this up properly. In the instructions, you have `local_commands` and in your example `config.json` you have `"direct": true`. Which of these is correct?

**Comment by THATDONFC** [comment]
Ok, I just tried a fresh install. Here were my steps

1. Add homebridge v2 smart app to smartthings ide
2. configure homebridge v2 smart app in smartthings classic app by adding all devices that were configured previously in homebridge-tonesto7
3. `rm -r /accessories`, `rm -r /persist`
4. Install homebridge v2 plugin in hoobs.
5. Configure `config.json` (my config below)
6. Start homebridge

Result: same error as before. 

My `config.json` entry:
```{
            "platform": "SmartThings-v2",
            "name": "SmartThings-v2",
            "app_url": "https://graph-na04-useast2.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "redacted app_id",
            "access_token": "redacted access_token",
            "temperature_unit": "F",
            "logConfig": {
                "debug": true,
                "showChanges": true,
                "hideTimestamp": false,
                "hideNamePrefix": false,
                "file": {
                    "enabled": true
                }
            },
            "plugin_map": {
                "plugin_name": "homebridge-smartthings-v2"
            }
        }
```
Log file:
```
[Homebridge] [12/12/2019, 6:32:43 AM] Loaded config.json with 2 accessories and 4 platforms.
[Homebridge] [12/12/2019, 6:32:45 AM] Loaded plugin: homebridge-smartthings-v2
[Homebridge] [12/12/2019, 6:32:45 AM] Registering platform 'homebridge-smartthings-v2.SmartThings-v2'
[Homebridge] [12/12/2019, 6:32:46 AM] Loading 4 platforms...
[Homebridge] [12/12/2019, 6:32:46 AM] [SmartThings-v2] Initializing SmartThings-v2 platform...
[Homebridge] [12/12/2019, 6:32:46 AM][SmartThings-v2]INFO: Homebridge Version: 2.4
[Homebridge] [12/12/2019, 6:32:46 AM][SmartThings-v2]INFO: SmartThings-v2 Plugin Version: 2.0.4
[Homebridge] [12/12/2019, 6:32:46 AM][SmartThings-v2]INFO: Checking Package Version for Updates...
[Homebridge] [12/12/2019, 6:32:46 AM][SmartThings-v2]INFO: Configure Cached Accessory: Front Door Contact Sensor, UUID: 876jdol7-764e-5r7n-k469-7856t7kj84m4
[Homebridge] [12/12/2019, 6:32:46 AM][SmartThings-v2]DEBUG: Initializing Cached Device MY_REMOVED_DEVICE_ID
[Homebridge] [12/12/2019, 6:32:46 AM][SmartThings-v2]DEBUG:
[Homebridge] [12/12/2019, 6:32:46 AM][SmartThings-v2]DEBUG: Setting device data from existing data
[Homebridge] [12/12/2019, 6:32:46 AM][SmartThings-v2]INFO: Configure Cached Accessory: Front Door Contact Sensor, UUID: 876jdol7-764e-5r7n-k469-7856t7kj84m4
[Homebridge] [12/12/2019, 6:32:47 AM][SmartThings-v2]DEBUG: Initializing Cached Device MY_REMOVED_DEVICE_ID
[Homebridge] [12/12/2019, 6:32:47 AM][SmartThings-v2]DEBUG:
[Homebridge] [12/12/2019, 6:32:47 AM][SmartThings-v2]DEBUG: Setting device data from existing data
[Homebridge] [12/12/2019, 6:32:47 AM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 876jdol7-764e-5r7n-k469-7856t7kj84m4
[Homebridge] at Bridge.Accessory.addBridgedAccessory (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:268:13)
[Homebridge] at Server._configCachedPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:407:22)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:85:10)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:82:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)
[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
[Homebridge] at startup (internal/bootstrap/node.js:283:19)
[Homebridge] at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[Homebridge] [12/12/2019, 6:32:47 AM][SmartThings-v2]ERROR: uncaughtException: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 9876jdol7-764e-5r7n-k469-7856t7kj84m4
[Homebridge] [12/12/2019, 6:32:48 AM][SmartThings-v2]INFO: INFO: Your plugin version is up-to-date
[Homebridge] [12/12/2019, 6:32:48 AM][SmartThings-v2]NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: null
[Homebridge] [12/12/2019, 6:32:49 AM][SmartThings-v2]DEBUG: sendUpdateStatus Resp:
```

**Comment by bkonings** [comment]
I seemed to have the same issue, I have two airco units.
Both seemed to show up in multiple sections of the SmartThings app. When I enabled everything there where 14 devices listed. Starting homebridge the same message appeared.
Once I only selected 2 devices the error disappeared an everything seems to work fine.
(I get temperature sensor, humidity sensor and on/off, a thermostat would have been nice but this is already awesome :) )

**Comment by tonesto7** [comment]
Should be resolved in the new v2.1.0 I just pushed out.

**Comment by THATDONFC** [comment]
Thank you @tonesto7 ! I’ll take another stab at installing this tonight.

**Comment by THATDONFC** [comment]
EDIT: This is on the 2.1.3 version
Looks like this is still an issue. I'm going to try a few different things to see if I can get this error to go away.

I've put *'s next to the lines where the device is initialized to make it easier to read.
Debug log included:
```[Homebridge] [1/8/2020, 7:43:26 AM] [SmartThings-v2] Initializing SmartThings-v2 platform...
[Homebridge] [1/8/2020, 7:43:26 AM][SmartThings-v2]INFO: Homebridge Version: 2.4
[Homebridge] [1/8/2020, 7:43:26 AM][SmartThings-v2]INFO: SmartThings-v2 Plugin Version: 2.1.3
[Homebridge] [1/8/2020, 7:43:27 AM][SmartThings-v2]INFO: Checking Package Version for Updates...
*[Homebridge] [1/8/2020, 7:43:27 AM][SmartThings-v2]INFO: Configure Cached Accessory: Front Door Contact Sensor, UUID: 900fbbe0-661d-4f8e-a975-4493e1fd26c5
*[Homebridge] [1/8/2020, 7:43:27 AM][SmartThings-v2]DEBUG: Initializing Cached Device 782dc3f0-f8c6-4798-8348-d86910bc5577
*[Homebridge] [1/8/2020, 7:43:27 AM][SmartThings-v2]DEBUG: Front Door Contact Sensor  |  contact_sensor
[Homebridge] [1/8/2020, 7:43:27 AM][SmartThings-v2]GOOD: [CHARACTERISTIC (function() {
[Homebridge] Characteristic.call(this, 'Contact Sensor State', '0000006A-0000-1000-8000-0026BB765291');
[Homebridge] this.setProps({
[Homebridge] format: Characteristic.Formats.UINT8,
[Homebridge] maxValue: 1,
[Homebridge] minValue: 0,
[Homebridge] validValues: [0,1],
[Homebridge] perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
[Homebridge] });
[Homebridge] this.value = this.getDefaultValue();
[Homebridge] }) GET] contact (Front Door Contact Sensor) | LastUpdate: (Wed Jan 08 2020 07:43:27 GMT-0800 (Pacific Standard Time)) | Value: (0)
[Homebridge] [1/8/2020, 7:43:27 AM][SmartThings-v2]GOOD: [CHARACTERISTIC (function() {
[Homebridge] Characteristic.call(this, 'Status Tampered', '0000007A-0000-1000-8000-0026BB765291');
[Homebridge] this.setProps({
[Homebridge] format: Characteristic.Formats.UINT8,
[Homebridge] maxValue: 1,
[Homebridge] minValue: 0,
[Homebridge] validValues: [0,1],
[Homebridge] perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
[Homebridge] });
[Homebridge] this.value = this.getDefaultValue();
[Homebridge] }) GET] tamper (Front Door Contact Sensor) | LastUpdate: (Wed Jan 08 2020 07:43:27 GMT-0800 (Pacific Standard Time)) | Value: (0)
*[Homebridge] [1/8/2020, 7:43:27 AM][SmartThings-v2]INFO: Configure Cached Accessory: Front Door Contact Sensor, UUID: 900fbbe0-661d-4f8e-a975-4493e1fd26c5
[Homebridge] [1/8/2020, 7:43:27 AM][SmartThings-v2]GOOD: [CHARACTERISTIC (function() {
[Homebridge] Characteristic.call(this, 'Contact Sensor State', '0000006A-0000-1000-8000-0026BB765291');
[Homebridge] this.setProps({
[Homebridge] format: Characteristic.Formats.UINT8,
[Homebridge] maxValue: 1,
[Homebridge] minValue: 0,
[Homebridge] validValues: [0,1],
[Homebridge] perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
[Homebridge] });
[Homebridge] this.value = this.getDefaultValue();
[Homebridge] }) GET] contact (Front Door Contact Sensor) | LastUpdate: (Wed Jan 08 2020 07:43:27 GMT-0800 (Pacific Standard Time)) | Value: (0)
[Homebridge] [1/8/2020, 7:43:27 AM][SmartThings-v2]GOOD: [CHARACTERISTIC (function() {
[Homebridge] Characteristic.call(this, 'Status Tampered', '0000007A-0000-1000-8000-0026BB765291');
[Homebridge] this.setProps({
[Homebridge] format: Characteristic.Formats.UINT8,
[Homebridge] maxValue: 1,
[Homebridge] minValue: 0,
[Homebridge] validValues: [0,1],
[Homebridge] perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
[Homebridge] });
[Homebridge] this.value = this.getDefaultValue();
[Homebridge] }) GET] tamper (Front Door Contact Sensor) | LastUpdate: (Wed Jan 08 2020 07:43:27 GMT-0800 (Pacific Standard Time)) | Value: (0)
*[Homebridge] [1/8/2020, 7:43:27 AM][SmartThings-v2]DEBUG: Initializing Cached Device 782dc3f0-f8c6-4798-8348-d86910bc5577
*[Homebridge] [1/8/2020, 7:43:27 AM][SmartThings-v2]DEBUG: Front Door Contact Sensor  |  contact_sensor
[Homebridge] [1/8/2020, 7:43:27 AM][SmartThings-v2]ERROR: uncaughtException: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 900fbbe0-661d-4f8e-a975-4493e1fd26c5
[Homebridge] [1/8/2020, 7:43:27 AM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 900fbbe0-661d-4f8e-a975-4493e1fd26c5
    at Bridge.Accessory.addBridgedAccessory (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:268:13)
    at Server._configCachedPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:360:22)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:82:10)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[Homebridge] [1/8/2020, 7:43:27 AM] Got SIGTERM, shutting down service...

**Comment by THATDONFC** [comment]
Ok, I did a "Factory Reset" in HOOBS and deleted/reinstalled the smart app. With a fresh install, everything works just fine, aside from #43.

**Comment by yaggayoyo** [comment]
Switched to HOOBS and installed Smarthings-V2 and just copied my JSON config from MAC Homebridge. Traffic seemed one way (Home to ST only, ST updates were not reflected in Home app) and error logs had "ERROR: sendUpdateStatus Error: true | Message: undefined". Spent 3 hours until I found this issue and @THATDONFC update to install V2 of tonesto7/homebridge-smartthings-v2. Installed and was fully operational in 10 mins. THANK YOU!! I was about to toss HOOBS.
