### ISSUE TITLE
Fridge does not show correct status. (BUG) 

### ISSUE THREAD

**Issue by pangsmart** [tonesto7/homebridge-smartthings-v2#13]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The SmartApp and Device Handler are using the latest code available.
-  [x ] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 1
-  Mobile App Version(Not required): Latest (iOS)
-  SmartApp Version: (Latest)
-  Device Handler Version:
-  Homebridge Version: 0.4.50
-  NodeJS Version: 12.13.1

## Expected Behavior
**Tell us what you think should be happening**
Homekit should reflect the state of fridge doors and the temperature of both the fridge and the freezer. 
## Current Behavior
**What happens instead of the expected behavior?**
Fridge is stuck on open state and temperature is stuck at 0 degrees.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

Add fridge according to instructions.

## Context
I am not able to check the state of my fridge (in case it is left open) or its temperature.
---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
I have a new version of the smartapp coming out this week with a device debug that allows you to select a device and it will show all attributes, capabilities, commands, and last 30 events. 
So you can share that info with me so I can help build support.
I will comment here when it's released.

**Comment by tonesto7** [comment]
Should be resolved in the new v2.1.0 I just pushed out.

**Comment by yannip1234** [comment]
Here is the device data and its attributes. The fridge contact sensor and temp is still showing incorrectly. Thanks.

{
    "name": "Refrigerator",
    "basename": "Refrigerator",
    "deviceid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "status": "ACTIVE",
    "manufacturer": "Unknown",
    "model": "Samsung OCF Refrigerator",
    "deviceNetworkId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "lastActivity": "2020-01-15T02:15:26+0000",
    "capabilities": [
        "Contact Sensor",
        "Execute",
        "Filter Status",
        "Ocf",
        "Power Consumption Report",
        "Refresh",
        "Refrigeration",
        "Temperature Measurement",
        "custom.deodorFilter",
        "custom.deviceReportStateConfiguration",
        "custom.disabledCapabilities",
        "custom.dthVersion",
        "custom.error",
        "custom.waterFilter"
    ],
    "commands": [
        "execute",
        "postOcfCommand",
        "printResources",
        "refresh",
        "resetDeodorFilter",
        "resetWaterFilter",
        "setDefrost",
        "setError",
        "setRapidCooling",
        "setRapidFreezing",
        "setReportStatePeriod",
        "setReportStateRealtime",
        "setReportStateRealtimePeriod"
    ],
    "customflags": [
        
    ],
    "attributes": {
        "contact": null,
        "data": "{\"payload\":{\"id\":\"2\",\"x.com.samsung.da.name\":\"CVRoom\",\"x.com.samsung.da.openState\":\"Close\"}}",
        "defrost": null,
        "deodorFilterCapacity": null,
        "deodorFilterResetType": null,
        "deodorFilterStatus": null,
        "deodorFilterUsage": null,
        "deodorFilterUsageStep": null,
        "di": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "disabledCapabilities": null,
        "dmv": "res.1.1.0,sh.1.1.0",
        "error": null,
        "filterStatus": null,
        "iceStatus": null,
        "icv": "core.1.1.0",
        "mndt": null,
        "mnfv": null,
        "mnhw": null,
        "mnml": null,
        "mnmn": "Samsung Electronics",
        "mnmo": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "mnos": null,
        "mnpv": null,
        "mnsl": null,
        "n": "Refrigerator",
        "pi": "shp",
        "powerConsumption": null,
        "rapidCooling": "Off",
        "rapidFreezing": "Off",
        "reportStatePeriod": null,
        "reportStateRealtime": null,
        "reportStateRealtimePeriod": null,
        "st": null,
        "temperature": null,
        "versionNumber": 19112601,
        "vid": "DA-REF-NORMAL-100001",
        "waterFilterCapacity": null,
        "waterFilterResetType": null,
        "waterFilterStatus": null,
        "waterFilterUsage": null,
        "waterFilterUsageStep": null
    },
    "eventHistory": [
        
    ]

**Comment by tonesto7** [comment]
That's because the contact attribute on the device is set to null

**Comment by yannip1234** [comment]
Oh strange. It works fine when I click the tile in the app though.
